[15.0][ADD] added new module fleet_payment
opticrd/governmental-odoo-modules pull request #54
Opened 2024-01-03 03:09 UTC by dixgrake

2024-01-04 03:19 UTC, dixgrake commented
@akevinieron check it

2024-01-22 12:30 UTC, akevinieron requested changes

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__init__.py
> +from . import models
Todos los documentos python deben terminar con una línea en blanco. Es una buena práctica del lenguaje.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +    'depends': ['base','fleet','l10n_do_accounting'],
Este listado no contiene todos los módulos que estás usando en el código. Por ej: estás usando account.journal y el módulo donde se encuentra ese modelo no está en este listado.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +        This module provides functionalities for managing payments related to vehicle fleets.
Cuáles funcionalidades?

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +    'summary': "Payment management for vehicle fleets",
El "Summary" está deprecated desde hace algún tiempo. No debes usarlo

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +    'website': "",
Incluye el website del ministerio

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +    'demo': [
Te recomiendo que agregues demo data. Si no lo harás para esta versión es mejor que elimines esto de aquí hasta que tengas algo que ponerle.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +    'version': '15.0.0.1.2',
Este control de versiones debería ser 15.0.0.1.0, porque hasta ahora no ha salido a producción ninguna versión de esto. Debes cambiar de versión según la planificación de salida a producción.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/__init__.py
> +from . import fleet_vehicle_log_services
Todos los documentos python deben terminar con una línea en blanco. Es una buena práctica del lenguaje.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +}
Todos los documentos python deben terminar con una línea en blanco. Es una buena práctica del lenguaje.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +from odoo.tools.translate import _
Este paquete lo debes importar desde "odoo", junto con modelo y campos. El ejemplo quedaría así: from odoo import models, fields, api, _

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +from datetime import datetime
Esto es una librería del lenguaje, debería ser la primera que importes y luego vienen las importaciones desde Odoo

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +        _name = 'fleet.method.payment'
Si te refieres a "Metodo de Pago" entonces esto debería llamarse "fleet.payment.method". Debes cambiar todas las referencias a este modelo para ajustarle el nombre

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +        bank = fields.Char(string='Bank', related='journal_id.bank_id.name', readonly=True)
"bank_name"*

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +        def action_set_active(self):
Sigue la convención usada por Odoo para este tipo de acciones.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +                result = []
Me parece que estás usando una identación muy ámplia. Aquí hay mucho más que 4 espacios

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +                for acc in self:
No debes usar disminutivos poco descriptivos. Busca una palabra que describa bien el objeto que vive en este variable y no lo abrevies, a menos que sea una convención.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +                        payment_form_label = payment_form_selection.get(acc.payment_form, acc.payment_form)
Pusiste el mismo valor en ambos parámetros del get. Eso no se ve como una buena idea. Revisa como funciona el método get en diccionarios y provecha sus beneficios.

2024-01-22 12:30 UTC, akevinieron commented on fleet_payment/models/fleet_method_payment.py
> +                        account_number_short = acc.account_number[-6:] if acc.account_number else 'XXXXXX'
Esta lógica llévala a un método que le pases el número y el te devuelva el número corto o las X

2024-01-22 14:56 UTC, dixgrake commented on fleet_payment/__manifest__.py
> +        This module provides functionalities for managing payments related to vehicle fleets.
- Metodo de Pago
- Informe de Servicio Personalizado

2024-01-22 14:58 UTC, akevinieron commented on fleet_payment/__manifest__.py
> +        This module provides functionalities for managing payments related to vehicle fleets.
Pero no lo dice!

2024-02-02 13:29 UTC, merged

2024-02-05 01:17 UTC, dixgrake commented
/deploy